var firstJoke = true;

var jokes = [
    "A man knocked on my door and asked for a small donation for a local swimming pool. So I gave him a glass of water.",
    "I went to a really emotional wedding the other day. Even the cake was in tiers.",
    "I was getting into my car the other day and a man said 'Can you give me a lift?' I said 'Sure, you look great, chase your dreams, go for it!'",
    "My wife and I were happy for years. But then we met.",
    "The thing about dwarfs and midgets is that they have very little in common.",
    "How do prisoners call each other? On their cell phones!",
    "Did you hear about the man who lost his entire left side in an accident? He's all right now.",
    "Claustrophobic people are more productive thinking outside the box.",
    "People who lack the patience for calligraphy will never have properly formed characters.",
    "What happened to the rich guy with the double chin? He made a four chin.",
    "The stripper was getting tired of the same old thong and dance.",
    "Waking up this morning was an eye-opening experience.",
    "I tripped over my wife's bra. It seemed to be a booby trap!",
    "She had a photographic memory but never developed it.",
    "My math teacher called me average. How mean!",
    "Sleeping comes so naturally to me, I can do it with my eyes closed.",
    "I had to quit my job at the shoe recycling factory. It was just sole destroying.",
    "What's the best time to go to the dentist? Tooth-hurtie!",
    "Butchers link sausage to make ends meat.",
    "Why didn't the lifeguard save the hippie? Because he was too far out, man.",
    "A train stops at a train station. A bus stops at a bus station. Now, why is my desk called a 'work station'?",
    "I used to be a banker, but over time I lost interest.",
    "The girl quit her job at the donut factory because she was fed up with the hole business.",
    "I went to a buffet dinner with my neighbor, who is a taxidermist. After such a big meal, I was stuffed.",
    "A lawyer-turned-cook is a sue chef.",
    "The food they serve to guards can last for sentries.",
    "How do construction workers party? They raise the roof.",
    "Tree trimmers do such a fantastic job, they should take a bough.",
    "The librarian didn't know what to do with the book about Tesla's love of electricity, so he filed it under 'Current Affairs.'",
    "After manually rotating the heavy machinery, the worker grew pretty cranky.",
    "The inept psychic attempted clairvoyance but just couldn't get intuit.",
    "The carpenter came round the other day. He made the best entrance I have ever seen...",
    "Telling a demolitionist how to do his job is destructive criticism.",
    "Old artists never retire, they withdraw instead!",
    "The key to job searching is looking deep within yourself. It's all about the inner view.",
    "The obstetricians seem to celebrate labor day every single day!",
    "The pilot was a loner but even for him flying a drone was simply too remote.",
    "What type of shirt does an astronaut wear? Apollo shirt.",
    "I slept like a log during the night shift and I was axed when I awoke!",
    "The incompetent telegrapher was a weapon of Morse destruction.",
    "A friend of mine tried to annoy me with bird puns, but I soon realized that toucan play at that game.",
    "The deer grabbed the gun and gave the hunter a taste of his own venison.",
    "Why did the bee get married? Because he found his honey.",
    "What would bears be without bees? Ears.",
    "What did the buffalo say to his son when he left for college? Bison.",
    "Why do seals swim in salt water? Because pepper water makes them sneeze.",
    "Pig puns are really boaring.",
    "Why don't lobsters give to charity? Because they're shellfish.",
    "Insects really bug me!",
    "A dog gave birth to puppies at the roadside and was fined for littering.",
    "The best way to communicate with a fish is to drop them a line.",
    "Cuddling a cat usually leaves you feline good.",
    "How does a farmer count his cows? With a cow-culator.",
    "Where did Noah keep his bees? In the ark hives.",
    "What do you call a magic dog? A Labracadabrador.",
    "What do you call bees that are fat? Obeese.",
    "I watched a beaver movie last week. It was the best dam movie ever.",
    "What do you call a cow eating grass? A lawn-mooer.",
    "What city has the largest rodent population? Hamsterdam.",
    "I've got a chicken-proof garden. It's completely impeccable!",
    "What do you call a cow with two legs? Lean beef.",
    "Which day do chickens hate the most? Fry-day.",
    "What do you call an alligator in a vest? Investigator.",
    "Have you ever heard of an honest cheetah?",
    "Why couldn't the chicken locate her eggs? Because she had mislaid them.",
    "What do you call a fish with no eyes? A fsh.",
    "Why are most horses so slim? Because they are on a stable diet!",
    "Why do cows wear bells? Because their horns don't work!",
    "I was going to tell my pizza joke but I think it's a bit too cheesy.",
    "What kind of pumpkin protects castles? A royal gourd!",
    "Even covered in salad dressing my lettuce looked bare, so I put some cloves on it.",
    "Where do witches bake their cakes? In a coven.",
    "Two loaves of bread wanted to get married, which is why they eloafed.",
    "I get distracted by all the meats in the deli section, must be my short attention spam.",
    "Did you hear about the sick Italian chef? Sadly, he pastaway.",
    "What are twins' favorite fruit? Pears!",
    "What did the baby corn say to its mom? Where's my popcorn?",
    "Did you hear the joke about the peanut butter? I'm not telling you. You might spread it!",
    "Who's the king of vegetables? Elvis Parsley.",
    "Why did the tomato blush? It saw the salad dressing!",
    "Waiter, will my pizza be long? No sir, actually it's round.",
    "Why couldn't the sesame seed leave the casino? It was on a roll.",
    "Why did the students eat their homework? Their teacher said it was a piece of cake.",
    "What does a nosey pepper do? Gets jalapeno business.",
    "What do you call an almond in space? An astronut.",
    "Why didn't the banana go to work? It wasn't peeling well.",
    "'Waiter, this food tastes funny...' 'Then why aren't you laughing?!'",
    "Why doesn't bread like warm weather? Because it makes things toasty!",
    "His beard is so thick that when he eats food he mustache some of it away for later.",
    "I always believed my body was a prison. I was right, in biology, I learned it was made of cells.",
    "The skeleton comic was trying tibia little humerus.",
    "Masks have no face value!",
    "Does my brand new smile denture ego?",
    "An umbilical cord is a navel vessel.",
    "My friend started telling me skeleton puns. They were all extremely rib tickling.",
    "How do you capture a skeleton? Use a rib-cage.",
    "I'm friends with my fist, even though he's quite a knuckle head.",
    "The cardiovascular system is a work of artery, but it is also pretty vein.",
    "Are you a sleepy skeleton? Because you look bone tired.",
    "What did the bra say to the hat? You go on a head while I give these a lift.",
    "His head may have been inches long, but he didn't use it as a ruler.",
    "A red blood count is a communist vampire.",
    "England doesn't have a kidney bank, but it does have a Liverpool.",
    "People who jump off bridges in Paris are in Seine.",
    "If you said you were from South America, I would not Bolivia.",
    "Tourists in Cuba are usually Havana great time!",
    "The Irish are wealthy since their capitol is always Dublin.",
    "Never make fun of a Scotsman's traditional garb. You might end up getting kilt!",
    "Italian building inspectors in Pisa are leanient.",
    "Things made in Australia are high koala-ty.",
    "Show me someone in denial and I'll show you a person in Egypt up to their ankles.",
    "I'd love to visit Holland, wooden shoe?",
    "Britain is a wet place due to the queen's long reign.",
    "The incontinent Scotsman had a wee accident.",
    "Goats in France are great musicians because they have French horns.",
    "Did you know that donuts were first made in Greece?",
    "A practical Czech is considered to be Praguematic.",
    "British TVs have to cross the English Channel.",
    "The pharaohs of Egypt came up with the first pyramid scheme.",
    "People in Switzerland can't learn to ski without a lot of alp.",
    "Never date a tennis player. Love means nothing to them.",
    "I wondered why the baseball was getting bigger. Then it hit me.",
    "Why don't some couples go to the gym? Because some relationships don't work out.",
    "Do beginner vampires go to batting practice?",
    "Since I quit soccer, I've lost my life goals.",
    "I lift weights only on Saturday and Sunday because Monday to Friday are weak days.",
    "I'm not a huge fan of archery. It has way too many drawbacks!",
    "My snowboarding skills are really going downhill fast!",
    "My tennis opponent was not happy with my service. He kept returning it.",
    "I quit gymnastics because I was fed up of hanging around the bars.",
    "A fisherman tried boxing, but he only threw hooks.",
    "What should you say to impatient jockeys? Hold your horses.",
    "The race car driver had a pretty checkered past...",
    "Why was the referee fired? Because he was a whistle blower!",
    "The weigh-in at the Sumo wrestling championship was a large scale effort.",
    "After a long time waiting for the bowling alley to open, we eventually got the ball rolling.",
    "I couldn't quite remember how to throw a boomerang, but eventually, it came back to me.",
    "Refusing to go to the gym counts as resistance training, right?",
    "I'm taking part in a stair climbing competition. Guess I better step up my game.",
    "Why do soccer players do so well in math? They know how to use their heads!",
    "My dog Minton ate all my shuttlecocks. Bad Minton!",
    "Why was Cinderella banned from playing sports? Because she always ran away from the ball.",
    "I know Jiu-Jitsu, Sambo, Judo, Aikido and lots of other scary words!",
    "I tried water polo but my horse drowned...",
    "To the guy who invented zero: Thanks for nothing!",
    "I hate Russian Dolls. They're so full of themselves.",
    "I was thinking about getting a brain transplant, but then I changed my mind.",
    "I can't understand why people are so bothered about me not knowing what the word 'apocalypse' means. It's not like it's the end of the world!",
    "Where do baby spoons come from? The spork delivers them.",
    "The British cannibal enjoyed snacking on fish and chaps.",
    "I tried to finish the leftovers, but they had been foiled again.",
    "The man's zipper broke, but he fixed it on the fly.",
    "Why can't you trust Satan's resume? The devil lies in the details.",
    "A hair raising experience sounds promising to a bald man.",
    "It was cold in the bedroom so I lay down in the fireplace and slept like a log.",
    "Don't spell 'part' backwards. It's a trap!",
    "When I get naked in the bathroom, I usually end up turning on the shower.",
    "Why don't cannibals eat clowns. They taste rather funny.",
    "I recently got crushed by a pile of books, but I suppose I've only got my shelf to blame.",
    "I've decided to sell my vacuum. Well, it was just gathering dust!",
    "I was overcharged for velcro last week. What a rip off!",
    "I saw a documentary on how ships are kept together. Riveting!",
    "I've been reading a book about anti-gravity. It's impossible to put down.",
    "Have you heard about the magic tractor? It turned into a field!",
    "My first job was at a calendar factory. I can't believe they sacked me, all I did was take a day off!",
    "I couldn't work out how to fasten my seatbelt for ages. But then one day, it just clicked.",
    "Yesterday I accidentally swallowed some food coloring. The doctor says I'm OK, but I feel like I've dyed a little inside.",
    "I'd tell you a chemistry joke but I know I wouldn't get a reaction.",
    "Have you ever tried to eat a clock? It's very time-consuming.",
    "I once got into so much debt that I couldn't even afford my electricity bills, they were the darkest times of my life.",
    "It's a lengthy article on Japanese Sword Fighters but I can Samurais it for you.",
    "I didn't use to like duct-tape at first, but I soon became attached to it.",
    "Even the smallest egg farms are multi-layer organizations.",
    "I understand how gems were made. The concept is crystal clear to me.",
    "The newspaper's rationale for running the story was paper thin.",
    "I really wanted a camouflage cap, but I couldn't find one.",
    "I planned to find my watch today, but I didn't have the time.",
    "How do the elves clean Santa's sleigh after Christmas? They use Santa-tizer!",
    "What do you call someone who can't stop thinking about Christmas? Santa-mental!",
    "Santa's beard is so long because he's bad at shaving. That's why they call him Saint Nick.",
    "Why did Santa watch a performance of the Nutcracker at the North Pole? He wanted to see some Pole dancing!",
    "What do Santa's little helpers eat on a cold day? Elf-abet soup!",
    "Santa owes a lot to his little helpers. One might say he's an elf-made man.",
    "What do you call an elf that runs away from Santa? A rebel without a Claus!",
    "Elves are always defending the shape of their ears. They make some good points.",
    "What did Santa's helper do to improve his toy-making skills? He read an elf-help book!",
    "What do you call a reindeer that suddenly forgets how to fly? The deerly departed!",
    "Did you hear the weather forecast for Christmas Eve? They're calling for rain, dear!",
    "How did Rudolph survive his first trip through the sky? He held on for deer life!",
    "What do you call a ghostly reindeer? Cari-boo!",
    "Did you know that reindeer like to gather in large groups? Yes, I herd!",
    "Did you hear about the couple whose car broke down on Christmas Eve? They got a mistletow!",
    "What does a cranky sheep say at Christmas? Baa humbug!",
    "Some people love eggnog, while others find it's not all it's cracked up to be.",
    "Who brings Christmas presents to good little puppies? Santa Paws!",
    "Kids who don't learn to tie their shoes properly are bound to wind up on the knotty list.",
    "What does a festive sheep say at Christmas? Fleece Navidad!"
];

var jButton = document.getElementById('jbutton');
if (jButton) {
    jButton.addEventListener('click', tellJoke(), false);
}

function tellJoke() {
    if (firstJoke) {
        var jokeButton = document.getElementById('jbutton');
        jokeButton.style.width = "310px";
        jokeButton.style.backgroundImage = "url('./assets/another.png')";
        jokeButton.style.marginLeft = "35%";
        firstJoke = false;
    }
    
    document.getElementById('jtext').innerHTML = jokes[Math.floor(Math.random() * jokes.length)];
}
